name: intellectra_ai
description: An AI Assistant (ChatBot,Image Generator & Language Translator). developed by Priyanshu Saraswat.

publish_to: 'none' 

# App Version
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

# Dependencies 
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  lottie: ^3.1.0
  # hive database
  # hive: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0
  #get pub 
  get: ^4.6.6
  # animate
  flutter_animate: ^4.5.0
  animated_text_kit: ^4.2.2
  #api call
  # http: ^1.1.0
  flutter_gemini: ^2.0.3
  image_picker: ^1.0.8
  dash_chat_2: ^0.0.20
  http: ^1.1.0
  # gallery_saver_updated: ^3.0.0
  share_plus: ^9.0.0
  flutter_riverpod: ^2.4.10
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

  # Encourages Good Practices
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/images/logo.png

  # To add assets to your application, add an assets section, like this:
  #assets:
  # - assets/images/logo.png
  # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
